In [1]:
import pandas as pd

In [2]:
path_dir = "./data/mexico-real-estate-1.csv"

In [4]:
df = pd.read_csv(path_dir)
df.head()

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

**method chaining**

In [14]:
(
    pd.read_csv(path_dir)
    .dropna()
    .info()
)

<class 'pandas.DataFrame'>
Index: 583 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  583 non-null    str
 1   state          583 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        583 non-null    float64
 5   price_usd      583 non-null    str
dtypes: float64(3), str(3)
memory usage: 31.9 KB

In [15]:
data = (
    pd.read_csv(path_dir)
    .dropna()
)

In [17]:
def clean_df(path):
    return (
    pd.read_csv(path_dir)
    .dropna()
)

In [18]:
data = clean_df(path_dir)
data.head()

  property_type             state        lat         lon  area_m2    price_usd
0         house  Estado de México  19.560181  -99.233528    150.0   $67,965.56
1         house        Nuevo León  25.688436 -100.198807    186.0   $63,223.78
2     apartment          Guerrero  16.767704  -99.764383     82.0   $84,298.37
3     apartment          Guerrero  16.829782  -99.911012    150.0   $94,308.80
5         house           Yucatán  21.052583  -89.538639    205.0  $105,191.37