In [22]:
import pandas as pd
import seaborn as sns

In [23]:
path = "dataset/train.csv"
df = pd.read_csv(path)
df = df.drop(columns=["id"])
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [24]:
# shape of data
df.shape

(188533, 12)

In [25]:
# information about the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   brand         188533 non-null  str
 1   model         188533 non-null  str
 2   model_year    188533 non-null  int64
 3   milage        188533 non-null  int64
 4   fuel_type     183450 non-null  str
 5   engine        188533 non-null  str
 6   transmission  188533 non-null  str
 7   ext_col       188533 non-null  str
 8   int_col       188533 non-null  str
 9   accident      186081 non-null  str
 10  clean_title   167114 non-null  str
 11  price         188533 non-null  int64
dtypes: int64(3), str(9)
memory usage: 17.3 MB

In [26]:
# missing values
missing_values_summary = pd.DataFrame({
    "count": df.isna().sum(),
    "percentage": round(df.isna().mean() * 100, 2)
})

missing_values_summary

              count  percentage
brand             0        0.00
model             0        0.00
model_year        0        0.00
milage            0        0.00
fuel_type      5083        2.70
engine            0        0.00
transmission      0        0.00
ext_col           0        0.00
int_col           0        0.00
accident       2452        1.30
clean_title   21419       11.36
price             0        0.00

In [31]:
df[df.isna().any(axis=1)]

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
11,Tesla,Model S P100D,2015,81500,NaN,Electric Motor Electric Fuel System,1-Speed A/T,Gray,White,None reported,Yes,19000
20,Land,Rover Defender S,2023,7978,Gasoline,5.2L V10 40V PDI DOHC,8-Speed Automatic,Santorini Black Metallic,Black,None reported,NaN,41998
32,Tesla,Model S P100D,2018,30300,NaN,518.0HP Electric Motor Electric Fuel System,A/T,White,White,None reported,Yes,64000
45,RAM,1500 Laramie,2022,27352,Gasoline,5.7L V8 16V MPFI OHV,8-Speed Automatic,Diamond Black,Black,None reported,NaN,42599
51,Tesla,Model 3 Long Range,2020,38360,NaN,Dual Motor - Standard,Automatic,White,Black,None reported,NaN,59598
...,...,...,...,...,...,...,...,...,...,...,...,...
188507,Chevrolet,Corvette Stingray w/3LT,2023,3053,Gasoline,490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,NaN,NaN,61999
188511,Land,Rover Range Rover Velar P380 SE R-Dynamic,2022,15198,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Firenze Red,Ebony,None reported,NaN,23739
188513,Lexus,GS 350 F Sport,2022,82046,Gasoline,3.5L V6 24V PDI DOHC,8-Speed Automatic,Caviar,Black,None reported,NaN,48990
188520,Mercedes-Benz,GLC 300 GLC 300,2022,18031,Gasoline,2.0 Liter Turbo,Automatic,White,Black,None reported,NaN,39998
188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900

In [44]:
df.loc[df["fuel_type"].isna(),["brand","engine"]].value_counts().head()

brand   engine
Tesla   518.0HP Electric Motor Electric Fuel System    743
        425.0HP Electric Motor Electric Fuel System    644
        455.0HP Electric Motor Electric Fuel System    463
Rivian  835.0HP Electric Motor Electric Fuel System    433
Tesla   670.0HP Electric Motor Electric Fuel System    280
Name: count, dtype: int64

In [50]:
df[df["fuel_type"].isna()]["engine"].str.contains(
    "Electric",
    case=False,
    na=False
).mean()

np.float64(0.9565217391304348)

In [58]:
df["accident"].value_counts(dropna=False)

accident
None reported                             144514
At least 1 accident or damage reported     41567
NaN                                         2452
Name: count, dtype: int64

In [59]:
df[df["accident"].isna()]["brand"]

87                  RAM
134                Jeep
164               Acura
333       Mercedes-Benz
361                 RAM
              ...
187885        Chevrolet
188140        Chevrolet
188425            Volvo
188505             Ford
188507        Chevrolet
Name: brand, Length: 2452, dtype: str

In [60]:
df[df["accident"].isna()].describe()

        model_year         milage         price
count  2452.000000    2452.000000  2.452000e+03
mean   2017.300163   50269.850734  5.490299e+04
std       5.577505   44729.872494  1.018028e+05
min    1974.000000     159.000000  2.000000e+03
25%    2015.000000   15192.250000  2.300000e+04
50%    2019.000000   36728.500000  3.899900e+04
75%    2021.000000   73690.000000  6.091925e+04
max    2024.000000  402000.000000  2.954083e+06

In [62]:
df[df["accident"].isna()].describe(include='str')

,brand,model,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
count,2452,2452,2383,2452,2452,2452,2452,0,14
unique,49,940,6,591,36,173,82,0,1
top,Ford,F-150 XLT,Gasoline,3.6L V6 24V MPFI DOHC,A/T,Black,Black,NaN,Yes
freq,322,60,2087,106,384,539,1337,NaN,14