In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv("data/Algerian_forest_fires_cleaned_dataset.csv")
df.head()

,day,month,year,temperature,rh,ws,rain,ffmc,dmc,dc,isi,bui,fwi,classes,region
0,1.0,6.0,2012.0,29.0,57.0,18.0,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0.0
1,2.0,6.0,2012.0,29.0,61.0,13.0,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,0.0
2,3.0,6.0,2012.0,26.0,82.0,22.0,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0.0
3,4.0,6.0,2012.0,25.0,89.0,13.0,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0.0
4,5.0,6.0,2012.0,27.0,77.0,16.0,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0.0

In [12]:
# drop month, day, year
df = df.drop(["month", 'day',"year"], axis=1)

In [16]:
df['classes']= df['classes'].str.strip()
df["classes"] = np.where(df["classes"].str.contains("not fire"),0,1)

In [18]:
df["classes"].value_counts()

classes
1    137
0    106
Name: count, dtype: int64

In [19]:
# indepedent and dependent features
X = df.drop("fwi", axis=1)
y = df["fwi"]

In [20]:
X.head()

   temperature    rh    ws  rain  ffmc  dmc    dc  isi  bui  classes  region
0         29.0  57.0  18.0   0.0  65.7  3.4   7.6  1.3  3.4        0     0.0
1         29.0  61.0  13.0   1.3  64.4  4.1   7.6  1.0  3.9        0     0.0
2         26.0  82.0  22.0  13.1  47.1  2.5   7.1  0.3  2.7        0     0.0
3         25.0  89.0  13.0   2.5  28.6  1.3   6.9  0.0  1.7        0     0.0
4         27.0  77.0  16.0   0.0  64.8  3.0  14.2  1.2  3.9        0     0.0

In [21]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X,y,
                                                     test_size=0.25,
                                                     random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((182, 11), (61, 11), (182,), (61,))

In [23]:
# feature selection based on correlation
X_train.corr()

,temperature,rh,ws,rain,ffmc,dmc,dc,isi,bui,classes,region
temperature,1.000000,-0.656095,-0.305977,-0.317512,0.694768,0.498173,0.390684,0.629848,0.473609,0.542141,0.254549
rh,-0.656095,1.000000,0.225736,0.241656,-0.653023,-0.414601,-0.236078,-0.717804,-0.362317,-0.456876,-0.394665
ws,-0.305977,0.225736,1.000000,0.251932,-0.190076,0.000379,0.096576,-0.023558,0.035633,-0.082570,-0.199969
rain,-0.317512,0.241656,0.251932,1.000000,-0.545491,-0.289754,-0.302341,-0.345707,-0.300964,-0.369357,-0.059022
ffmc,0.694768,-0.653023,-0.190076,-0.545491,1.000000,0.620807,0.524101,0.750799,0.607210,0.781259,0.249514
dmc,0.498173,-0.414601,0.000379,-0.289754,0.620807,1.000000,0.868647,0.685656,0.983175,0.617273,0.212582
dc,0.390684,-0.236078,0.096576,-0.302341,0.524101,0.868647,1.000000,0.513701,0.942414,0.543581,-0.060838
isi,0.629848,-0.717804,-0.023558,-0.345707,0.750799,0.685656,0.513701,1.000000,0.643818,0.742977,0.296441
bui,0.473609,-0.362317,0.035633,-0.300964,0.607210,0.983175,0.942414,0.643818,1.000000,0.612239,0.114897
classes,0.542141,-0.456876,-0.082570,-0.369357,0.781259,0.617273,0.543581,0.742977,0.612239,1.000000,0.188837
region,0.254549,-0.394665,-0.199969,-0.059022,0.249514,0.212582,-0.060838,0.296441,0.114897,0.188837,1.000000