### Change the Data types

In [17]:
import pandas as pd

In [18]:
drinks = pd.read_csv("http://bit.ly/drinksbycountry")

In [19]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [20]:
drinks.dtypes

country                             str
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                           str
dtype: object

In [21]:
drinks["beer_servings"]=drinks.beer_servings.astype(float)

In [22]:
drinks.dtypes

country                             str
beer_servings                   float64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                           str
dtype: object

**how to define type of column before actually reading the csv?**

In [23]:
drinks = pd.read_csv("http://bit.ly/drinksbycountry", dtype={'beer_servings':float})

In [24]:
drinks.dtypes

country                             str
beer_servings                   float64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                           str
dtype: object

In [26]:
orders = pd.read_csv("http://bit.ly/chiporders", sep="\t")

In [27]:
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [28]:
orders.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [31]:
orders.item_price.str.replace("$","").astype(float).mean()

np.float64(7.464335785374297)

In [36]:
orders.item_name.str.contains("Chicken").astype(int).head()

0    0
1    0
2    0
3    0
4    1
Name: item_name, dtype: int64