### How do i read a tabular data file into pandas?

In [1]:
import pandas as pd

In [3]:
orders = pd.read_table("http://bit.ly/chiporders")

In [4]:
# first 5 rows
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [10]:
user_cols = ["user_id", "age","gender", "occupation", "zip_code"]
users = pd.read_table("http://bit.ly/movieusers", sep="|", header = None, names = user_cols)
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

**Bonus tips**

In [16]:
orders = pd.read_table("http://bit.ly/chiporders", skiprows =[1,2,3])
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
1,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
2,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
3,3,1,Side of Chips,NaN,$1.69
4,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75